test:
	../env/bin/python manage.py test main

runserver:
	../env/bin/python manage.py runserver 8000

migration:
	../env/bin/python manage.py schemamigration main --auto

migrate:
	../env/bin/python manage.py migrate main

dbshell:
	../env/bin/python manage.py dbshell

