test:
	python manage.py test main www api services

runserver:
	python manage.py runserver 8000

migration:
	python manage.py schemamigration main --auto

migrate:
	python manage.py migrate main

dbshell:
	python manage.py dbshell

